apiVersion: ENC[AES256_GCM,data:ARo=,iv:k3Zom9/41wW+uDCTfvGvRBbzj5TzhBEWnaz2HPpcRw8=,tag:5E2Hn2o/rg1N+UNgWwbtxA==,type:str]
kind: ENC[AES256_GCM,data:pCZErQiR,iv:65vt+xpIQZZLbAbYNsVu69YcsQvleQqCWG5dxHQJtM8=,tag:CCnLAeD7tpjOrH5kt6+POw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J+dk00z7FoE14hrTk6g=,iv:WiF2vJJZ5DHOXa4yab+yhE/inDvj6QBaykXtrqCkZwE=,tag:dRslD3C24HnZuPQqBzfAMA==,type:str]
    namespace: ENC[AES256_GCM,data:cDwS2Xt/YtF/0tU=,iv:BMMEVWC0ImVn6FJQ3aiOc2EfOvrzrqMzyLjfftbbCu4=,tag:EVjS/uqWgU3IAhopUP0heA==,type:str]
type: ENC[AES256_GCM,data:q9wivEBEWIcfTzAnMcryGSMP6fBu0rOx75PfvXQN,iv:+BiG4Pq5j41+c0Pn0/O7HKjXkMV7xa0PsA3SAW3v14I=,tag:yQUQYMP1G9VCe/OfavP+3Q==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:zOTlrU564ewNSi27tTjwdw3w6HayCurYXCanB35TEh+Vj8sKT7lTGnxOiHiJL/wR4GBvKommp0COOX7h3MuGCtX6EfuzKb0ezuB0Y77AoyxI2ZDXQ6iVleo2YEId7TWboR3rQbg2G3w+fD5YSQZPAe+cVnM3JuNaCRDqHRZl/6PTlkijX6bMcEqU1kreioOAb+uVfYPNVoyFQnVkmcjB3dluxVvziYG1JHgzM4/t6inxZ4ml,iv:DE45RkLDE4wZD94+aSLmb8fQ6r9CZ2/Tj9bpNZvNJr0=,tag:2KrLYvRKzlhUdmoh7reMqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y3hLamU2dmMwM0wrTEhW
            WDU0Mzh2TUFFV3pmdWFQdE1ZMWtFeG9kakZBCjg1VzI0UWhqbFN3aHBGd2FFWXR4
            QlZiQ0h1L3NPMENXN0hvYlNzMG9GVkkKLS0tIHpEN1dDZElqU2FlbGtjNjRkVmFG
            QnFpbC94WVRDZHIyMWNvQmkyNzlQYUkKVw36w65YT5hDoSN/PtT2Lz31Z2QjqjvO
            Idq+h4Q+4AWFl7hCHY1gtaqeLxx+e1BS8OEdV5wfygL3TJtr2kUPWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-03T12:39:04Z"
    mac: ENC[AES256_GCM,data:X8Zlh2Uw4uvpji8SSETTDM1pHhwesMjaUVXcovEGbNPJKksUkcBNYegsbe6mH1NzEZ5Zx53yjlmtwu8R6rQFdy5GC8xeYlAOpYkl4b4JOGsjNN8uBnNYI9AkCdiyZAvBqZJa9HI7c+g1Xcc8vF+uMdLKslgAZVVXc9Jsas1h/X4=,iv:c3Oiz/yumXBLDVNeaYtIr1HIx52pdxdcjAtIpI8L/v8=,tag:ggg/VA5e7LPMERonyXJ22A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
